# Generated by Django 5.0.1 on 2024-01-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoFacility",
            fields=[
                ("loc", models.TextField(blank=True, db_column="LOC", null=True)),
                (
                    "fac_popu",
                    models.BigIntegerField(blank=True, db_column="FAC_POPU", null=True),
                ),
                (
                    "qur_rate",
                    models.TextField(blank=True, db_column="QUR_RATE", null=True),
                ),
                (
                    "std_day",
                    models.TextField(blank=True, db_column="STD_DAY", null=True),
                ),
                (
                    "cf_idx",
                    models.BigIntegerField(
                        db_column="CF_IDX", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "co_facility",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CoPopuDensity",
            fields=[
                ("loc", models.TextField(blank=True, db_column="LOC", null=True)),
                ("popu_density", models.BigIntegerField(blank=True, null=True)),
                (
                    "qur_rate",
                    models.TextField(blank=True, db_column="QUR_RATE", null=True),
                ),
                (
                    "std_day",
                    models.TextField(blank=True, db_column="STD_DAY", null=True),
                ),
                (
                    "cp_idx",
                    models.BigIntegerField(
                        db_column="CP_IDX", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "co_popu_density",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CoVaccineThird",
            fields=[
                ("loc", models.TextField(blank=True, db_column="LOC", null=True)),
                (
                    "std_day",
                    models.TextField(blank=True, db_column="STD_DAY", null=True),
                ),
                (
                    "third_rate",
                    models.BigIntegerField(
                        blank=True, db_column="Third_RATE", null=True
                    ),
                ),
                (
                    "qur_rate",
                    models.TextField(blank=True, db_column="QUR_RATE", null=True),
                ),
                (
                    "cv_idx",
                    models.BigIntegerField(
                        db_column="CV_IDX", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "co_vaccine_third",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CoWeekday",
            fields=[
                ("index", models.TextField()),
                ("fri", models.FloatField(blank=True, db_column="FRI", null=True)),
                ("mon", models.FloatField(blank=True, db_column="MON", null=True)),
                ("sat", models.FloatField(blank=True, db_column="SAT", null=True)),
                ("sun", models.FloatField(blank=True, db_column="SUN", null=True)),
                ("the", models.FloatField(blank=True, db_column="THE", null=True)),
                ("tue", models.FloatField(blank=True, db_column="TUE", null=True)),
                ("wed", models.FloatField(blank=True, db_column="WED", null=True)),
                (
                    "std_day",
                    models.TextField(
                        db_column="STD_DAY", primary_key=True, serialize=False
                    ),
                ),
            ],
            options={
                "db_table": "co_weekday",
                "managed": False,
            },
        ),
    ]
